spring.application.name=movies
spring.mongodb.database=${env.MONGO_DATABASE}
spring.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}/movies
server.port=${env.SERVER_PORT:8080}
app.cors.allowed-origins=${env.CORS_ALLOWED_ORIGINS:http://localhost:3000}

app.tmdb.base-url=https://api.themoviedb.org/3
app.tmdb.image-base-url=https://image.tmdb.org/t/p
app.tmdb.api-token=${env.TMDB_API_TOKEN:}
app.tmdb.trending-limit=10

springdoc.override-with-generic-response=false
springdoc.api-docs.enabled=${env.API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${env.API_DOCS_ENABLED:true}